version: "3.8"

services:
  postgres:
    image: postgres:13
    container_name: postgres
    environment:
      POSTGRES_USER: airflow
      POSTGRES_PASSWORD: airflow
      POSTGRES_DB: airflow
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - mlops-net

  airflow-webserver:
    build: ./mlops-airflow
    container_name: airflow-webserver
    depends_on:
      - postgres
    environment:
      AIRFLOW__CORE__EXECUTOR: LocalExecutor
      AIRFLOW__CORE__SQL_ALCHEMY_CONN: postgresql+psycopg2://airflow:airflow@postgres:5432/airflow
      AIRFLOW__CORE__LOAD_EXAMPLES: "False"
      AIRFLOW__WEBSERVER__EXPOSE_CONFIG: "True"
      AIRFLOW__WEBSERVER__SECRET_KEY: "super_secret_key_1234"
    ports:
      - "8080:8080"
    volumes:
      - ./mlops-airflow/dags:/opt/airflow/dags
      - ./mlops-airflow/plugins:/opt/airflow/plugins
      - /var/run/docker.sock:/var/run/docker.sock
    command: webserver
    networks:
      - mlops-net

  airflow-scheduler:
    build: ./mlops-airflow
    container_name: airflow-scheduler
    depends_on:
      - postgres
    environment:
      AIRFLOW__CORE__EXECUTOR: LocalExecutor
      AIRFLOW__CORE__SQL_ALCHEMY_CONN: postgresql+psycopg2://airflow:airflow@postgres:5432/airflow
      AIRFLOW__WEBSERVER__SECRET_KEY: "super_secret_key_1234"
    volumes:
      - ./mlops-airflow/dags:/opt/airflow/dags
      - ./mlops-airflow/plugins:/opt/airflow/plugins
      - /var/run/docker.sock:/var/run/docker.sock
    command: scheduler
    networks:
      - mlops-net

  mlflow-server:
    build: ./mlops-mlflow
    container_name: mlflow-server
    ports:
      - "5050:5050"
    volumes:
      - ./mlops-mlflow/src:/app/src:ro
      - ./mlops-mlflow/log:/app/log
    working_dir: /app/src
    env_file:
      - .env
    command: >
      mlflow ui
      --backend-store-uri file:/app/log
      --default-artifact-root s3://mlops-weather/data/model
      --host 0.0.0.0
      --port 5050
    networks:
      - mlops-net

volumes:
  postgres_data:

networks:
  mlops-net:
    name: mlops-net
    driver: bridge