global:
  scrape_interval: 15s
  evaluation_interval: 15s

rule_files:
  - "/etc/prometheus/rules/*.yml"

alerting:
  alertmanagers:
    - static_configs:
        - targets:
          - alertmanager:9093

scrape_configs:

  # Prometheus itself
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']
  

  # Node Exporter for system metrics
  - job_name: 'node-exporter'
    static_configs:
      - targets: ['node-exporter:9100']

  # API Server health check
  #- job_name: 'api-server'
  #  static_configs:
  #    - targets: ['api-server:8000']
  #  scrape_interval: 10s

  # Inference Server health check
  #- job_name: 'inference-server'
  #  static_configs:
  #    - targets: ['inference-server:8001']
  #  scrape_interval: 10s

  # Airflow health check
  #- job_name: 'airflow'
  #  static_configs:
  #    - targets: ['airflow-webserver:8080']
  #  scrape_interval: 30s