name: Build and Test with Docker Compose

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up Docker Compose
        uses: docker/setup-compose-action@v2
        # 또는 최신 버전 확인 후 입력

      - name: Build and start services
        run: docker compose up -d --build

      - name: Test services (optional)
        run: |
          docker compose exec airflow-webserver airflow version


      - name: Stop and clean up
        if: always()
        run: docker compose down
